### ISSUE TITLE
Отсутствие RecCityName в итоговом запросе на доставку курьером

### ISSUE THREAD

**Issue by MirAlexSky** [sanmai/cdek-sdk#102]
При создании CdekOrder и указании RecCityName в массиве RecCity запрос уходит без  RecCityName. В нормальной ситуации cdek видит город по индексу (postcode), но бывает, что он не находит город. Поддержка cdek советует добавить поле с именем для запроса, хотя это поле я вообще нашёл только в документации по cdek api 2.0, а в 1.5 нет.

Пример:

```
$cdekOrder = new Order([
           ...
            'RecCity' => City::create([
                'PostCode' => $recipient->getPostcode(),
                'CityName' => $recipient->getCityName(),
            ]),
           ...
]);
```

Должен отправиться запрос с полем RecCityName, но этого поля нет

**Comment by iamwildtuna** [comment]
Просто **Name**, а не **CityName**.

**Comment by sanmai** [comment]
![](https://user-images.githubusercontent.com/139488/109004045-8ffc4980-76eb-11eb-8772-7189a4bbdd08.png)

**Comment by MirAlexSky** [comment]
Отлично, то что нужно! Спасибо большое!
