### ISSUE TITLE
Новый Content-Type "application/atom+xml" для ответа

### ISSUE THREAD

**Issue by brnsk-1945** [sanmai/cdek-sdk#103]
**Опишите проблему**
Вызов метода "Получение списка городов", возвращает ErrorResponse с телом  {"text": "ok", "errorCode":200}. Я обратил внимание, что теперь в ответе получаем заголовок Content-Type: application/atom+xml Проверка isTextResponse возвращает false и получаем ErrorResponse.

**Шаги для повторения проблемы**
http://integration.cdek.ru/v1/location/cities/xml?size=1&cityName=%D0%91%D1%80%D1%8F%D0%BD%D1%81%D0%BA&page=0
Посмотреть заголовки

**Ожидаемое поведение**
Должна загрузится информация о городе

**Контекст**
object(CdekSDK\Responses\ErrorResponse)#3030 (1) { ["response":"CdekSDK\Responses\ErrorResponse":private]=> object(GuzzleHttp\Psr7\Response)#3026 (6) { ["reasonPhrase":"GuzzleHttp\Psr7\Response":private]=> string(2) "OK" ["statusCode":"GuzzleHttp\Psr7\Response":private]=> int(200) ["headers":"GuzzleHttp\Psr7\Response":private]=> array(9) { ["Server"]=> array(1) { [0]=> string(5) "nginx" } ["Date"]=> array(1) { [0]=> string(29) "Wed, 17 Feb 2021 19:56:46 GMT" } ["Content-Type"]=> array(1) { [0]=> string(20) "application/atom+xml" } ["Transfer-Encoding"]=> array(1) { [0]=> string(7) "chunked" } ["Connection"]=> array(1) { [0]=> string(10) "keep-alive" } ["Cache-Control"]=> array(1) { [0]=> string(13) "max-age=18000" } ["X-Content-Type-Options"]=> array(1) { [0]=> string(7) "nosniff" } ["X-XSS-Protection"]=> array(1) { [0]=> string(13) "1; mode=block" } ["X-Frame-Options"]=> array(1) { [0]=> string(4) "DENY" } } ["headerNames":"GuzzleHttp\Psr7\Response":private]=> array(9) { ["server"]=> string(6) "Server" ["date"]=> string(4) "Date" ["content-type"]=> string(12) "Content-Type" ["transfer-encoding"]=> string(17) "Transfer-Encoding" ["connection"]=> string(10) "Connection" ["cache-control"]=> string(13) "Cache-Control" ["x-content-type-options"]=> string(22) "X-Content-Type-Options" ["x-xss-protection"]=> string(16) "X-XSS-Protection" ["x-frame-options"]=> string(15) "X-Frame-Options" } ["protocol":"GuzzleHttp\Psr7\Response":private]=> string(3) "1.1" ["stream":"GuzzleHttp\Psr7\Response":private]=> object(GuzzleHttp\Psr7\Stream)#3023 (7) { ["stream":"GuzzleHttp\Psr7\Stream":private]=> resource(713) of type (stream) ["size":"GuzzleHttp\Psr7\Stream":private]=> NULL ["seekable":"GuzzleHttp\Psr7\Stream":private]=> bool(true) ["readable":"GuzzleHttp\Psr7\Stream":private]=> bool(true) ["writable":"GuzzleHttp\Psr7\Stream":private]=> bool(true) ["uri":"GuzzleHttp\Psr7\Stream":private]=> string(10) "php://temp" ["customMetadata":"GuzzleHttp\Psr7\Stream":private]=> array(0) { } } } }

**Comment by KoIIIeY** [comment]
Аналогично, за одно и корзина в сайте померла.

**Comment by sanmai** [comment]
Присылайте исправления, [здесь надо три строчки добавить](https://github.com/sanmai/cdek-sdk/blob/c16ae66e2de093d176d9802b8d4418d22fb46fab/src/CdekClient.php#L320-L336). И тест для этого всего.

**Comment by KoIIIeY** [comment]
Я могу так же сказать, что пример для получения регионов тоже помер, по другим причинам, но все же.

**Comment by sanmai** [comment]
Ну или пишите в поддержку СДЭК. Это явно какое-то ошибочное поведение.

**Comment by KoIIIeY** [comment]
Я был уверен, что этот репозиторий - официальный сдековский :)

Но в общем - сдек перестал возвращать данные в полях где есть ext, типа codeExt, там теперь лежит null, а по коду ожидается int. 

https://cdek-sdk.readthedocs.io/#RegionsRequest

$region->getCodeExt(); - вот тут будет ошибка что возвращается не int

**Comment by sanmai** [comment]
Сможете сделать отдельный тикет? Может кто соберётся поправить, или что.
