### ISSUE TITLE
сдек перестал возвращать данные в полях где есть ext, типа codeExt, там теперь лежит null, а по коду ожидается int.

### ISSUE THREAD

**Issue by KoIIIeY** [sanmai/cdek-sdk#104]
**Опишите проблему**
Но в общем - сдек перестал возвращать данные в полях где есть ext, типа codeExt, там теперь лежит null, а по коду ожидается int.

https://cdek-sdk.readthedocs.io/#RegionsRequest

$region->getCodeExt(); - вот тут будет ошибка что возвращается не int

**Шаги для повторения проблемы**
Просто выполнить код из примера по ссылке выше

**Ожидаемое поведение**
Нет ошибки, данные возвращаются

**Контекст**
Если это проблема с запросов или ответом API СДЭК, приведите текст ответа. Его можно получить из отладочного лога.

**Comment by sanmai** [comment]
Вам нужно обновить версию:
```
composer require -W sanmai/cdek-sdk:^0.7
```
