### ISSUE TITLE
как добавить дополнительные сервисы к заказу

### ISSUE THREAD

**Issue by Born2Rock** [sanmai/cdek-sdk#106]
Подскажите пожалуйста как добавить дополнительные сервисы к заказу:

```php
$services = new AdditionalService;
$order->addService($services->SERVICE_TRY_AT_HOME); //ПРИМЕРКА НА ДОМУ
$order->addService($services->SERVICE_PARTIAL_DELIVERY); //ПРИМЕРКА НА ДОМУ
$order->addService($services->SERVICE_CARGO_CHECK); //ПРИМЕРКА НА ДОМУ
```

В таком стиле не полулилось

**Comment by iamwildtuna** [comment]
Вот так:
`$order->addService(AdditionalService::create(AdditionalService::SERVICE_TRY_AT_HOME));`

**Comment by sanmai** [comment]
Здесь есть пример в контексте:

https://cdek-sdk.readthedocs.io/#AddDeliveryRequest
