### ISSUE TITLE
Кривая документация

### ISSUE THREAD

**Issue by StasToken** [sanmai/cdek-sdk#108]
Смотрю я такой пример: https://cdek-sdk.readthedocs.io/#CalculationWithTariffListRequest  
И он не работает... а почему? потому что забыли расказать что лежит в $client 
Где она определена то? и такой пример не один ниже тоже с этим косяком идет. 
добавте: 
`$client = new \CdekSDK\CdekClient('account', 'password');`
Что бы люди понимали что в $client  лежит эгземпляр класса \CdekSDK\CdekClient

**Comment by iamwildtuna** [comment]
@StasToken  про это написано в разделе https://cdek-sdk.readthedocs.io/#initialize. Нет смысла дублировать везде - это раздувание документации лишним дублированием одинаковых строк.
