### ISSUE TITLE
PHPDoc не воспринимается в PHPStorm

### ISSUE THREAD

**Issue by TiGR** [sanmai/cdek-sdk#20]
![image](https://user-images.githubusercontent.com/281226/49154649-0140cc80-f32a-11e8-8e8e-977ec94d3a88.png)

![image](https://user-images.githubusercontent.com/281226/49154547-ad35e800-f329-11e8-99ec-b99a94800518.png)

В PHPStorm не воспринимаются нотации вида

https://github.com/sanmai/cdek-sdk/blob/eb09d8fac42c791bedf70410879cab4fe8404ad7/src/CdekClient.php#L52

https://github.com/sanmai/cdek-sdk/blob/eb09d8fac42c791bedf70410879cab4fe8404ad7/src/CdekClient.php#L58

https://github.com/sanmai/cdek-sdk/blob/eb09d8fac42c791bedf70410879cab4fe8404ad7/src/CdekClient.php#L60

https://github.com/sanmai/cdek-sdk/blob/eb09d8fac42c791bedf70410879cab4fe8404ad7/src/CdekClient.php#L63-L64

Однако, если убрать `<Common\*>` всё начинает работать. Я, кстати, не в курсе что это за нотация, в phpDoc не могу найти.

**Comment by sanmai** [comment]
Это формат для дженериков, который то приходит в стандарты, то уходит. PHPStorm его [пока не поддерживает](https://youtrack.jetbrains.com/issue/WI-31960) в таком виде. 

Если так, как ниже, то работает?
```
 * @method Responses\RegionsResponse<Common\Region>|Responses\RegionsResponse sendRegionsRequest(Requests\RegionsRequest $request)
 * @method Responses\CitiesResponse<Common\Location>|Responses\CitiesResponse sendCitiesRequest(Requests\CitiesRequest $request)
```

**Comment by sanmai** [comment]
Psalm мне очень помогает с поиском ошибок и общей проверкой кода на корректность, так что, прямо скажу, вот так сходу отказаться от Psalm я не могу. Буду думать.

**Comment by TiGR** [comment]
Может разработчиков Psalm подтолкнуть в нужном направлении?

**Comment by sanmai** [comment]
Psalm уже работает с таким форматом как у PHPStorm, но здесь, почему-то, не понимает. Так или иначе сначала мне надо разобраться нет ли у меня какого-то недочёта, потом только придумать кейс и уже обращаться к разработчикам.

**Comment by sanmai** [comment]
Сейчас проблема остаётся?

**Comment by TiGR** [comment]
Метод теперь есть в подсказках, но при итерации тип не определяется:
![image](https://user-images.githubusercontent.com/281226/51822706-2df36f00-22ee-11e9-8eae-2e35b34db9ed.png)

**Comment by TiGR** [comment]
Так не работает, работает только так:
```php
    /**
     * @return Location[]|\ArrayIterator<array-key, Location>
     */
    public function getIterator()
    {
        return new \ArrayIterator($this->getItems());
    }
```

**Comment by sanmai** [comment]
Спасибо, исправлено в master. Пожалуйста, проверьте.

**Comment by TiGR** [comment]
Да, сейчас всё работает, спасибо. Кстати, PHPStorm воспринимает нотацию `Location[]|\ArrayIterator<array-key, Location>` вот так:

![image](https://user-images.githubusercontent.com/281226/51899220-9eb88b00-23c3-11e9-8671-525d59fa8cc0.png)

То есть, видимо, его парсер PHPDoc ломается на конструкции `Type<...>`
