### ISSUE TITLE
Ошибка создания заказа в yii1

### ISSUE THREAD

**Issue by ansaus** [sanmai/cdek-sdk#22]
В yii 1 происходит ошибка при отправке запроса на создание заказа

строка из примера где возникает ошибка
$client->sendDeliveryRequest($request);

ошибка:

```
include(see.php): failed to open stream: No such file or directory (framework\yii-1.1.14\framework\YiiBase.php:427)

#0 framework\yii-1.1.14\framework\YiiBase.php(427): CWebApplication->handleError()
#1 framework\yii-1.1.14\framework\YiiBase.php(427): include()
#2 unknown(0): autoload()
#3 unknown(0): spl_autoload_call()
#4 www\protected\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\AnnotationRegistry.php(165): class_exists()
#5 www\protected\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\DocParser.php(469): loadAnnotationClass()
#6 www\protected\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\DocParser.php(718): Doctrine\Common\Annotations\DocParser->classExists()
#7 www\protected\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\DocParser.php(663): Doctrine\Common\Annotations\DocParser->Annotation()
#8 www\protected\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\DocParser.php(354): Doctrine\Common\Annotations\DocParser->Annotations()
#9 www\protected\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\AnnotationReader.php(405): Doctrine\Common\Annotations\DocParser->parse()
#10 www\protected\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\AnnotationReader.php(338): Doctrine\Common\Annotations\AnnotationReader->collectParsingMetadata()
#11 www\protected\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\AnnotationReader.php(218): Doctrine\Common\Annotations\AnnotationReader->getClassImports()
#12 www\protected\vendor\jms\serializer\src\JMS\Serializer\Metadata\Driver\AnnotationDriver.php(68): Doctrine\Common\Annotations\AnnotationReader->getClassAnnotations()
#13 www\protected\vendor\jms\metadata\src\Metadata\MetadataFactory.php(87): JMS\Serializer\Metadata\Driver\AnnotationDriver->loadMetadataForClass()
#14 www\protected\vendor\jms\serializer\src\JMS\Serializer\GraphNavigator.php(193): Metadata\MetadataFactory->getMetadataForClass()
#15 www\protected\vendor\jms\serializer\src\JMS\Serializer\Serializer.php(177): JMS\Serializer\GraphNavigator->accept()
#16 www\protected\vendor\jms\serializer\src\JMS\Serializer\Serializer.php(96): JMS\Serializer\Serializer->visit()
#17 unknown(0): JMS\Serializer\Serializer->JMS\Serializer\{closure}()
#18 www\protected\vendor\phpoption\phpoption\src\PhpOption\Some.php(89): call_user_func()
#19 www\protected\vendor\jms\serializer\src\JMS\Serializer\Serializer.php(99): PhpOption\Some->map()
#20 www\protected\vendor\sanmai\cdek-sdk\src\Serialization\Serializer.php(133): JMS\Serializer\Serializer->serialize()
#21 www\protected\vendor\sanmai\cdek-sdk\src\CdekClient.php(211): CdekSDK\Serialization\Serializer->serialize()
#22 www\protected\vendor\sanmai\cdek-sdk\src\CdekClient.php(283): CdekSDK\CdekClient->serialize()
#23 www\protected\vendor\sanmai\cdek-sdk\src\CdekClient.php(150): CdekSDK\CdekClient->extractOptions()
#24 www\protected\vendor\sanmai\cdek-sdk\src\CdekClient.php(174): CdekSDK\CdekClient->sendRequest()
#25 www\protected\modules\admin\controllers\OrderController.php(416): CdekSDK\CdekClient->__call()
#26 framework\yii-1.1.14\framework\web\actions\CInlineAction.php(49): OrderController->actionSendOrderToCDEK()
#27 framework\yii-1.1.14\framework\web\CController.php(308): CInlineAction->runWithParams()
#28 framework\yii-1.1.14\framework\web\filters\CFilterChain.php(133): OrderController->runAction()
#29 framework\yii-1.1.14\framework\web\filters\CFilter.php(40): CFilterChain->run()
#30 framework\yii-1.1.14\framework\web\CController.php(1145): CAccessControlFilter->filter()
#31 framework\yii-1.1.14\framework\web\filters\CInlineFilter.php(58): OrderController->filterAccessControl()
#32 framework\yii-1.1.14\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#33 framework\yii-1.1.14\framework\web\filters\CFilter.php(40): CFilterChain->run()
#34 framework\yii-1.1.14\framework\web\CController.php(1145): CAccessControlFilter->filter()
#35 framework\yii-1.1.14\framework\web\filters\CInlineFilter.php(58): OrderController->filterAccessControl()
#36 framework\yii-1.1.14\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#37 framework\yii-1.1.14\framework\web\CController.php(291): CFilterChain->run()
#38 framework\yii-1.1.14\framework\web\CController.php(265): OrderController->runActionWithFilters()
#39 framework\yii-1.1.14\framework\web\CWebApplication.php(282): OrderController->run()
#40 framework\yii-1.1.14\framework\web\CWebApplication.php(141): CWebApplication->runController()
#41 framework\yii-1.1.14\framework\base\CApplication.php(180): CWebApplication->processRequest()
#42 www\index.php(19): CWebApplication->run()
```

**Comment by ansaus** [comment]
версии пакетов

doctrine/annotations        v1.6.0  Docblock Annotations Parser
doctrine/instantiator       1.1.0   A small, lightweight utility to instan...
doctrine/lexer              v1.0.1  Base library for a lexer that can be u...
google/recaptcha            1.2.1   Client library for reCAPTCHA, a free s...
guzzlehttp/guzzle           6.3.3   Guzzle is a PHP HTTP client library
guzzlehttp/promises         v1.3.1  Guzzle promises library
guzzlehttp/psr7             1.5.2   PSR-7 message implementation that also...
jms/metadata                1.7.0   Class/method/property metadata managem...
jms/parser-lib              1.0.0   A library for easily creating recursiv...
jms/serializer              1.13.0  Library for (de-)serializing data of a...
pclzip/pclzip               2.8.2   A PHP library that offers compression ...
phpcollection/phpcollection 0.5.0   General-Purpose Collection Library for...
phpoffice/phpexcel          1.8.2   PHPExcel - OpenXML - Read, Create and ...
phpoption/phpoption         1.5.0   Option Type for PHP
psr/http-message            1.0.1   Common interface for HTTP messages
psr/log                     1.1.0   Common interface for logging libraries
ralouphie/getallheaders     2.0.5   A polyfill for getallheaders.
sanmai/cdek-sdk             v0.6.12 СДЭК PHP SDK, библиотека...
sanmai/pipeline             v3.0.1  General purpose collections pipeline
vkcom/vk-php-sdk            0.2.0   VK PHP SDK

**Comment by ansaus** [comment]
после добавления той строчки ошибка все равно сохраняется

**Comment by ansaus** [comment]
возможно конфликт с автозагрузчиком yii 1 т.к. там еще не поддерживаются namespace

**Comment by ansaus** [comment]
после трассировки выяснил что почему то в классе doctrine annotations DocParser функция parse неверно определяет слово see как имя класса в следующем тексте
/**
 * Class DeliveryRequest.
 *
 * @see DeleteRequest
 *
 * @JMS\XmlRoot(name="DeliveryRequest")
 *
 * @final
 */
в результате вызывается конечный автозагрузчик из yii в котором и возникает ошибка

**Comment by ansaus** [comment]
проблема в автозагрузчике yiibase фреймворка yii 1
когда к нему в функцию автозагрузки попадает класс вида 'see.php' то он после всех возможных проверок все равно пытается его подключить include('see.php') в то время как автозагрузчик от composer loadClass такой файл не находит и удачно проходит дальше.

пока решение такое , откалючать автозагрузчик yii перед вызовом методов этого компонента

            spl_autoload_unregister(array('YiiBase','autoload'));
            $response = $client->sendDeliveryRequest($request);
            spl_autoload_register(array('YiiBase','autoload'));

**Comment by sanmai** [comment]
DocParser вроде как должен пропускать `@see` так как эта пометка [в списке игнорируемых по умолчанию](https://github.com/doctrine/annotations/blob/d393f679ae572f4735531882b62c1bc60bf5d33c/lib/Doctrine/Annotations/AnnotationReader.php#L38). 

Ссылки на исходники для дальнейшего разбирательства:

https://github.com/doctrine/annotations/blob/c7f2050c68a9ab0bdb0f98567ec08d80ea7d24d5/lib/Doctrine/Common/Annotations/AnnotationRegistry.php#L165

https://github.com/yiisoft/yii/blob/f0fee98ee84f70f1f3652f65562c9670e919cb4e/framework/YiiBase.php#L427

Что если поставить более новую версию фреймворка? Или только этого класса? Я вижу что есть 1.1.20.

**Comment by sanmai** [comment]
Исправление ушло в yiisoft/yii#4240

**Comment by sanmai** [comment]
Пишут что другой вариант решения:
```php
Yii::$enableIncludePath = false;
```

**Comment by ansaus** [comment]
спасибо! да проблема решена устоновкой Yii::$enableIncludePath = false;
