### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by srnden** [sanmai/cdek-sdk#25]
Если явно не указывать код страны (как в примере в readme), при запросе списка регионов, то в выборку попадают регионы других стран с пустыми значениями некоторых полей. 

![image](https://user-images.githubusercontent.com/16322716/52201991-40395400-287e-11e9-8ce0-7d3cba408544.png)

https://github.com/sanmai/cdek-sdk/blob/b6e6c7d8b8ee49fad336d80c5f282b64d84a5fca/src/Common/Region.php#L122
`Return value of CdekSDK\Common\Region::getCode() must be of the type integer, null returned`

**Comment by srnden** [comment]
Мне кажется так подход не очень правильный. Если есть необходимость в жесткой проверки типа пришедших от сервера данных, не лучше ли выбрасывать исключение. И кстати, есть ли эта необходимость в данном случае? Плюс в документации написано, что  приходит строка (10), а не инт.
![image](https://user-images.githubusercontent.com/16322716/52203715-0880db00-2883-11e9-8623-6c35e1652ebb.png)
Ещё я не знаю заранее код страны. Не нашел я способ вывести список стран. Я его узнал только при вардампе объекта Region.
Также, я не уверен на 100%, что в РФ все поля в регионах/городах заполнены.:)

**Comment by sanmai** [comment]
https://github.com/sanmai/cdek-sdk/blob/b6e6c7d8b8ee49fad336d80c5f282b64d84a5fca/src/Common/Region.php#L142

Отсюда можно узнать код страны, а уже зная его делать или не делать вызов к коду региона. В документации СДЭК местами путаница с видами значений, и даже вот написано что это поле - обязательное. А на деле - не строка, и не обязательное.

Но дело не в этом. Дело в том что если здесь поменять тип на другой, то другой код, который использует этот метод, ожидая на выходе `int`, станет неисправным. Значит по всем понятиям для этого исправления нужно выпускать major версию. Чего хотелось бы избежать.

**Comment by srnden** [comment]
Не понял, этот же метод относится к регионам. Мне необходимо знать countryCode до выборки регионов. Не делать же мне выборку 2 раза без setCountryCode и с ним. Или я чего-то не понимаю)
TypeError да вы правы.

**Comment by sanmai** [comment]
Покажите весь ваш код, пожалуйста.

**Comment by srnden** [comment]
Лучше вы. Каков алгоритм получения регионов определённой страны, например, России? Код страны в бд сдэк заранее не известен.

**Comment by sanmai** [comment]
Код страны в БД СДЭК заранее известен. Код у них [соответствуют ОКСМ](https://classifikators.ru/oksm). В документации об этом [пишется открытым текстом](https://confluence.cdek.ru/pages/viewpage.action?pageId=15616129#id-%D0%9F%D1%80%D0%BE%D1%82%D0%BE%D0%BA%D0%BE%D0%BB%D0%BE%D0%B1%D0%BC%D0%B5%D0%BD%D0%B0%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D0%BC%D0%B8(v1.5)-4.3.1.%D0%9E%D0%BF%D0%B8%D1%81%D0%B0%D0%BD%D0%B8%D0%B5%D0%BF%D0%B5%D1%80%D0%B5%D0%B4%D0%B0%D0%B2%D0%B0%D0%B5%D0%BC%D1%8B%D1%85%D0%BF%D0%BE%D0%BB%D0%B5%D0%B9%D0%B7%D0%B0%D0%BF%D1%80%D0%BE%D1%81%D0%B0).

**Comment by srnden** [comment]
Зачем тогда вы мне указываете на getCountryCode:) Эта функция возвращает не код ОКСМ. В любом случае, получить список стран без танцев с бубном не возможно, о чем просто я упомянул в начале. Хотя issue не по этому поводу вообще)

**Comment by sanmai** [comment]
Поддерживать список кодов стран - это задача для какого-то другого проекта. Я не вижу как могу вам помочь.

**Comment by ptandDev** [comment]
Коллеги, ошибку то можно обработать, если код региона null прилетает, а как города получить в этом случае? Там же код региона надо передавать или код страны. Но если у меня селекты страна, регион, город, то как быть?

**Comment by sanmai** [comment]
Что на этот вопрос ТП СДЭК отвечает? Мы ведь не можем получить коды если их нет в ответе API.
