### ISSUE TITLE
when sending bulk orders, you cannot get an error with the order ID

### ISSUE THREAD

**Issue by jexme** [sanmai/cdek-sdk#26]
in the DeliveryResponse class, you cannot get the private variable orders, there is no getter for it, when accessing the getOrders getter, $this->completeOrders is returned. Therefore, you cannot get errors with the order ID. Yes, there is a getMessages method, but from there you cannot get the identifier (order ID) in which the error occurred. Perhaps you can do this in some other way, but my attempts were unsuccessful.

this is a CdekSDK\Responses\DeliveryResponse class

**Comment by sanmai** [comment]
Care to show an XML response where this is a problem? They’re changing responses now and then, so I won’t be surprised if this is actually an issue, only need something to test against.

**Comment by jexme** [comment]
yes, of course, here is the answer in the form of xml
`<?xml version="1.0" encoding="UTF-8"?>
<response>
    <Order Number="156215" ErrorCode="ERR_NEED_ATTRIBUTE" Msg="Отсутствие обязательного атрибута: PVZCODE"/>
    <Order Number="156107" ErrorCode="ERR_RECCITYPOSTCODE" Msg="Почтовый индекс города получателя отсутствует в базе СДЭК: RecCityPostCode=999999"/>
    <Order Msg="Добавлено заказов 0"/>
</response>
`

**Comment by jexme** [comment]
да, конечно, вот ответ в виде xml
`<?xml version="1.0" encoding="UTF-8"?> <response> <Order Number="156215" ErrorCode="ERR_NEED_ATTRIBUTE" Msg="Отсутствие обязательного атрибута: PVZCODE"/> <Order Number="156107" ErrorCode="ERR_RECCITYPOSTCODE" Msg="Почтовый индекс города получателя отсутствует в базе СДЭК: RecCityPostCode=999999"/> <Order Msg="Добавлено заказов 0"/> </response>`

**Comment by jexme** [comment]
да, конечно, вот ответ в виде xml
`<?xml version="1.0" encoding="UTF-8"?> <response> <Order Number="156215" ErrorCode="ERR_NEED_ATTRIBUTE" Msg="Отсутствие обязательного атрибута: PVZCODE"/> <Order Number="156107" ErrorCode="ERR_RECCITYPOSTCODE" Msg="Почтовый индекс города получателя отсутствует в базе СДЭК: RecCityPostCode=999999"/> <Order Msg="Добавлено заказов 0"/> </response>`

**Comment by jexme** [comment]
yes, of course, here is the answer in the form of ХML
`<?xml version="1.0" encoding="UTF-8"?>
<response>
    <Order Number="156215" ErrorCode="ERR_NEED_ATTRIBUTE" Msg="Отсутствие обязательного атрибута: PVZCODE"/>
    <Order Number="156107" ErrorCode="ERR_RECCITYPOSTCODE" Msg="Почтовый индекс города получателя отсутствует в базе СДЭК: RecCityPostCode=999999"/>
    <Order Msg="Добавлено заказов 0"/>
</response>
`

**Comment by jexme** [comment]
it may be worth adding the getAllOrders method, which will return all the orders sent, and from there you can get an error and OrderId, or in the getMessage method add OrderId

**Comment by andrei26916** [comment]
Hi. Prompt as it is correct to do a log of requests of the module. The documentation is not clear.
