### ISSUE TITLE
Как отследить логи запросов?

### ISSUE THREAD

**Issue by siberiadev** [sanmai/cdek-sdk#27]
Подскажите как можно отслеживать логи запросов, которые мы отсылаем в СДЭК?
Спасибо.

**Comment by sanmai** [comment]
Как здесь:

https://github.com/sanmai/cdek-sdk#%D0%9E%D1%82%D0%BB%D0%B0%D0%B4%D0%BA%D0%B0-%D0%BF%D0%BE%D0%BB%D1%83%D1%87%D0%B0%D0%B5%D0%BC%D1%8B%D1%85-%D0%BE%D1%82%D0%B2%D0%B5%D1%82%D0%BE%D0%B2

Пример использования, если у вас нет своего подходящего логгера:

https://github.com/sanmai/cdek-sdk/blob/master/tests/Integration/TestCase.php#L61
https://github.com/sanmai/cdek-sdk/blob/master/tests/Integration/DebuggingLogger.php#L34

**Comment by siberiadev** [comment]
Огромное спасибо, попробуем)

**Comment by sanmai** [comment]
Получилось?

**Comment by sanmai** [comment]
Если что-то всё-таки не так, дайте знать. Пока закрываю.
