### ISSUE TITLE
Обработка ошибок

### ISSUE THREAD

**Issue by melenchenko** [sanmai/cdek-sdk#3]
Не фиксируются ошибки при вызове курьера и ошибка дублирования заказа с таким же Number при создании отправления.

**Comment by sanmai** [comment]
По первому куда смотреть? 

По второму API СДЭК не считает повторное создание с тем же номером - ошибкой. Впрочем, это логично и правильно.

**Comment by sanmai** [comment]
Попробуйте на новой версии, пожалуйста.

Если проблема остается, нужны примеры ответов API. [Получить их можно в логе.](https://github.com/sanmai/cdek-sdk#%D0%9E%D1%82%D0%BB%D0%B0%D0%B4%D0%BA%D0%B0-%D0%BF%D0%BE%D0%BB%D1%83%D1%87%D0%B0%D0%B5%D0%BC%D1%8B%D1%85-%D0%BE%D1%82%D0%B2%D0%B5%D1%82%D0%BE%D0%B2) Или можно запустить интеграционные тесты.

**Comment by sanmai** [comment]
Не похоже чтобы эту проблему можно было более воспроизвести в новой версии. Закрываю. 

Если будут повторы, дайте знать.
