### ISSUE TITLE
Order::getSenderCity() возвращает null

### ISSUE THREAD

**Issue by overvoidjs** [sanmai/cdek-sdk#32]
При любом телодвижении падают ошибки на подобии:

Fatal error: Uncaught TypeError: Return value of CdekSDK\Common\Order::getSenderCity() must be an instance of CdekSDK\Common\City, null returned in /var/www/html/vendor/sanmai/cdek-sdk/src/Common/Order.php:807 Stack trace: #0 /var/www/html/api/test.php(24): CdekSDK\Common\Order->getSenderCity() #1 {main} thrown in /var/www/html/vendor/sanmai/cdek-sdk/src/Common/Order.php on line 807

Что делать, как лечить? Возможно документацию как то не так понял?

**Comment by sanmai** [comment]
Что за ответ присылает СДЭК? [Как посмотреть запросы и ответы.](https://github.com/sanmai/cdek-sdk#%D0%9E%D1%82%D0%BB%D0%B0%D0%B4%D0%BA%D0%B0-%D0%BF%D0%BE%D0%BB%D1%83%D1%87%D0%B0%D0%B5%D0%BC%D1%8B%D1%85-%D0%BE%D1%82%D0%B2%D0%B5%D1%82%D0%BE%D0%B2)

**Comment by sanmai** [comment]
[Об обработке ошибок вида TypeError.](https://github.com/sanmai/cdek-sdk#typeerror)
