### ISSUE TITLE
Invalid datetime в отчете "Статусы заказов"

### ISSUE THREAD

**Issue by yurcha** [sanmai/cdek-sdk#41]
Пытаюсь получить статусы заказов, до последней строки этого все работает, а потом вылетает ошибка `Invalid datetime "2019-04-08", expected format Y-m-d\TH:i:sP`.

        $orders = Order::where('date', '>=', '2019-01-01')->whereNull('statusCode')->get();
        $request = new Requests\StatusReportRequest();
        $request->setChangePeriod(new ChangePeriod(new \DateTime('-1 day'), new \DateTime('+1 day')));
        foreach ($orders as $order) {
            $request->addOrder(Common\Order::withDispatchNumber($order->orderId));
        }
        $response = $client->sendStatusReportRequest($request);

![Безымянный](https://user-images.githubusercontent.com/31619105/55802792-a1c9a900-5ae1-11e9-98dc-9fdeadc168bd.png)
![Безымянный](https://user-images.githubusercontent.com/31619105/55802971-143a8900-5ae2-11e9-9183-2a8f980941e3.png)

P.S. Решил понять из за каких заказов вылетает эта ошибка, сужал запрос и пришел к тому, что все ломалось из за одного заказа. Но он ни чем не отличался от других. Статус у него был Вручен. Исключил этот заказ из запроса - все заработало. Но так и не понятно осталось почему из за него все ломалось.

**Comment by sanmai** [comment]
Это ошибка рассериализации. Значит СДЭК где-то присылают короткую дату без времени, когда [по документации](https://confluence.cdek.ru/pages/viewpage.action?pageId=15616129) обязывались присылать полную дату и время. К сожалению, нет более простого способа узнать на каком поле такая ошибка кроме как посмотрев исходный XML.

[Как подключить отладку запросов и ответов API.](https://github.com/sanmai/cdek-sdk#%D0%BE%D1%82%D0%BB%D0%B0%D0%B4%D0%BA%D0%B0-%D0%BF%D0%BE%D0%BB%D1%83%D1%87%D0%B0%D0%B5%D0%BC%D1%8B%D1%85-%D0%BE%D1%82%D0%B2%D0%B5%D1%82%D0%BE%D0%B2)

**Comment by sanmai** [comment]
Исправление будет аналогичное 781dd1fa2acdf3b2e5aa9a868e2bcff8415a4120

**Comment by sanmai** [comment]
Попробуйте на новой версии с этим заказом, пожалуйста. Должно сказать в каком именно поле наблюдается странная дата.

**Comment by sanmai** [comment]
Если не возражаете, пока закроем. Если же проблема всё ещё наблюдается, напишите.

**Comment by AntistressStore** [comment]
$request->setChangePeriod(new Common\ChangePeriod(new \DateTime('2020-01-29'), new \DateTime('2021-01-29')));

Failed to deserialize DateLastChange="2020-01-29 00:00:00+03:00": Invalid datetime "2020-01-29 00:00:00+03:00", expected one of the format "Y-m-d H:i:s".

И другие способы пробовал -11 day и назначал переменные и все равно возникает ошибка

**Comment by AntistressStore** [comment]
$st = new \DateTime('2020-01-29');
$st->format('Y-m-d H:i:s');  тоже не помогает, также как введение даты запрашиваемого формата  new \DateTime('2020-01-29 00:00:00')

**Comment by sanmai** [comment]
На какой версии это наблюдается?

**Comment by AntistressStore** [comment]
composer show sanmai/cdek-sdk
name     : sanmai/cdek-sdk
descrip. : СДЭК PHP SDK, библиотека для работы с API СДЭК
keywords : cdek, delivery, sdk, СДЭК, служба доставки
versions : * 0.7.2
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
homepage : https://cdek-sdk.readthedocs.io/
names    : sanmai/cdek-sdk

support
chat : https://t.me/phpcdeksdk
docs : https://cdek-sdk.readthedocs.io/
issues : https://github.com/sanmai/cdek-sdk/issues
source : https://github.com/sanmai/cdek-sdk/tree/0.7.2

autoload
psr-4
CdekSDK\ => src/

requires
ext-json *
ext-libxml *
ext-simplexml *
guzzlehttp/guzzle ^6.3 || ^7.0
php ^7.3 || ^8.0
psr/log ^1.0
sanmai/cdek-sdk-serializer ^0.2.6
sanmai/pipeline ^5.0

requires (dev)
ergebnis/composer-normalize ^2.9 <2.10 || ^2.0
friendsofphp/php-cs-fixer ^2.14
gamez/psr-testlogger ^3.0
illuminate/support >=5.2
infection/infection >=0.18
laravel/framework >=5.2
orchestra/testbench >=3
phan/phan ^1 <1.3 || >1.3.0
php-coveralls/php-coveralls ^2.1
phpstan/phpstan >=0.10
phpunit/phpunit ^9.4
sanmai/phpunit-legacy-adapter ^6 || ^8
vimeo/psalm >=3.0.16

suggests
ext-ctype For flexible attribute name handling
hughgrigg/php-business-time Finds next working day, helps with delivery estimates
monolog/monolog For advanced logging and debugging
sanmai/cdek-info For related constant enumerations and references
sanmai/hoa-protocol If you have trouble with a conflicting resolve()
sanmai/pindx For postal code validation

**Comment by sanmai** [comment]
Это другая проблема, в ответе СДЭК. Сделайте новый issue, приложив данные ответа СДЭК. И посмотрим, может у кого-то будет желание и силы поправить.
