### ISSUE TITLE
Нельзя указать только клиентский номер

### ISSUE THREAD

**Issue by lexsurkov** [sanmai/cdek-sdk#42]
В методе "Статусы заказов" нельзя указать только клиентский номер. 

В АПИ СДЭК указано обязательные поля в теги `Order` это `DispatchNumber`, `Number`, `Date`, но на практике это не так, можно указать например поле `Number` и получить статус по клиентскому номеру. К сожалению SDK не дает такой возможности. 

Необходимо добавить в класс `Common\Order` метод `withNumber()`. Что вы об этом думаете?

**Comment by sanmai** [comment]
Никакие особенные методы для этого не нужны. Используйте просто:
```php
$order = Order::create([
    'Number' => $Number,
]);
```

**Comment by lexsurkov** [comment]
Спасибо! Это работает. С методом было бы удобнее )))
