### ISSUE TITLE
mbstring.func_overload

### ISSUE THREAD

**Issue by Kossin7** [sanmai/cdek-sdk#43]
Работаю с битриксом. У него необходимое значение mbstring.func_overload = 2
При подключении sdk, выдает ошибку
`require_once $_SERVER['DOCUMENT_ROOT'].'/personal/api-dev/cdek/cdek-sdk-master/vendor/autoload.php';`

http://joxi.ru/nAyRxkgTgG0oQr

Подскажите как быть?

**Comment by iamwildtuna** [comment]
Только в [либе](https://github.com/amphp/byte-stream) убирать [эту проверку](https://github.com/amphp/byte-stream/blob/master/lib/functions.php#L10) и помечать в composer не обновлять ее.

**Comment by Kossin7** [comment]
> Только в [либе](https://github.com/amphp/byte-stream) убирать [эту проверку](https://github.com/amphp/byte-stream/blob/master/lib/functions.php#L10) и помечать в composer не обновлять ее.

Тоже думал об этом, но как-то казалось не камельфо. Повысил версию php до 7.3 все ошибки ушли.
