### ISSUE TITLE
Автокомплит списка городов

### ISSUE THREAD

**Issue by WalkingDexter** [sanmai/cdek-sdk#46]
Нет метода для автокомплита списка городов.
Пример - https://api.cdek.ru/city/getListByTerm/json.php?q=Москва

**Comment by sanmai** [comment]
Этот же метод доступен по JSONP, так что есть всё, чтобы делать его вызов прямо на клиенте, не проксируя запросы через сервер:

http://api.cdek.ru/city/getListByTerm/jsonp.php?q=%D0%9C%D0%BE%D1%81%D0%BA%D0%B2%D0%B0&callback=foo
