### ISSUE TITLE
Нумерация версий по semver?

### ISSUE THREAD

**Issue by TiGR** [sanmai/cdek-sdk#5]
Про нумерацию версий в README.md сказано следующее:

> Если вы установили когда-то версию ветки 0.5, например 0.5.7, то после обновления до 0.5.8 или даже до 0.5.12 вы можете рассчитывать что весь ваш код будет работать точно так же как раньше, без необходимости что-то менять, при условии, конечно, что API самих СДЭК не поменялось. Такого же принципа работы с версиями по умолчанию придерживается Composer.

Вроде бы composer придерживается [semver](https://semver.com/lang/ru). Там немного другой подход. Где breaking changes происходят только при смене первой цифры. Конечно там есть оговорка про версии начинающиеся с 0 (т.е., до первого официального стабильного релиза API), но в целом всё выглядит так:

> Учитывая номер версии МАЖОРНАЯ.МИНОРНАЯ.ПАТЧ, следует увеличивать:
> 1. МАЖОРНУЮ версию, когда сделаны обратно несовместимые изменения API.
> 2. МИНОРНУЮ версию, когда вы добавляете новую функциональность, не нарушая обратной совместимости.
> 3. ПАТЧ-версию, когда вы делаете обратно совместимые исправления.

Может быть лучше держаться семвера?

**Comment by sanmai** [comment]
Composer придерживается порядку версий именно в таком ключе. До версии 1.0 обозначение такое 0.МАЖОРНАЯ.МИНОРНАЯ.ПАТЧ. Это значит что 0.5 и 0.6 - это разные мажорные версии с точки зрения композера по умолчанию.

[Из мануала:](https://getcomposer.org/doc/articles/versions.md#caret-version-range-)

> For pre-1.0 versions it also acts with safety in mind and treats `^0.3` as `>=0.3.0 <0.4.0`.

**Comment by sanmai** [comment]
С другой стороны, выпускать при каждом изменении новую версию вида 0.6, 0.7... это большое неудобство для пользователей. Так как, опять же, композер ставит все с кареткой `^` до версии, а значит если человек установил версию 0.6, то он не получит 0.7 пока не зайдет и руками не поменяет требования к версии. А нам потом выслушивать жалобы вот прямо здесь, объяснять людям что из-за того что мы не используем особенности композера им нужно руками версию обновить. Разве это будет хорошо?

**Comment by TiGR** [comment]
Как я уже сказал, есть оговорка про версии до 0.х, и как раз в этих версиях оно работает так. 0.breakingChanges.minorChanges.patches. И поэтому каретка работает по-разному до нуля и после. Цитата оттуда же:

```js
// ^ | doesn't allow breaking changes (major version fixed - following semver)
"vendor/package": "^1.3.2", // >=1.3.2 <2.0.0
"vendor/package": "^0.3.2", // >=0.3.2 <0.4.0 // except if major version is 0
```

Также, мне кажется, что библиотека в таком состоянии, что в любой момент по сути можно сделать уже версию 1.0, а дальше следовать уже обычному семверу. Просто в README ничего не сказано что это только про нулевые версии правило и что с версии 1 breaking changes будут не во втором номере версии, а в первом. Из ридми как раз можно сделать заключение, что это правило для всех версий, и что совместимость может ломаться при смене второго номера версии.

Просто в этом плане показателен пример Symfony vs Laravel. Laravel постоянно вводит breaking changes при смене минорной версии. В то время как в Symfony совместимость гарантируется внутри мажорной версии. Из-за этого пользователи Laravel знают насколько проблематичнее обновлять зависимости ларавела, это делается не просто через `composer update` а ещё и через ручной разбор руководства по апгрейду. И так каждый раз.

**Comment by sanmai** [comment]
Дельное замечание, действительно стоит дополнить им README.

**Comment by sanmai** [comment]
Дополнено в a0ca71f, спасибо большое!
