### ISSUE TITLE
Накладная PDF выводится не в той кодировке

### ISSUE THREAD

**Issue by oleglap68** [sanmai/cdek-sdk#53]
Я установил ваш модуль для интеграции со СДЭКом.

 У меня при создании PDF-файла заказа в браузер выводятся кракозябры
 вместо квитанции СДЭК.

 Я просто возвращаю результат на экран браузера: 
```php
return (string) $response->getBody();
```
 Подскажите, что я делаю не так и как поддержать проект?

**Comment by sanmai** [comment]
Браузер показывает крякозябры потому что он не знает, что это PDF. Нужно сообщить ему об этом заголовком:
```php
header("Content-Type: application/pdf");
```

**Comment by oleglap68** [comment]
Я не пойму куда этот заголовок прицепить. У меня из формы в контроллер летит номер накладной, там идет обращение к Вашему коду, который заканчивается return (string) $response->getBody();
Заголовок, наверное, должен прописываться на этапе создания документа, может быть в методе getBody() или где?

**Comment by sanmai** [comment]
Прямо над этой строкой, если не заморачиваться. Иначе смотрите в документации к вашему фреймворку про добавление заголовков в ответ.

Внутри `getBody` ничего не нужно менять.

**Comment by oleglap68** [comment]
Прямо над строкой не получается. Спасибо, буду разбираться с фреймворком.
