### ISSUE TITLE
Не оформляются заказы с частичной доставкой с ошибкой "нет прав на оформление частичной доставки"

### ISSUE THREAD

**Issue by oleglap68** [sanmai/cdek-sdk#54]
При оформлении заказа с доп. услугами: примерка на дому, осмотр вложения - заказ оформляется правильно. А если добавить "частичную доставку", то выдает ошибку - нет прав на оформление частичной доставки. 
Писал в тех. поддержку СДЭК - третьи сутки молчат.
Может подскажете - это у них, или меня ошибка.

**Comment by sanmai** [comment]
Вы всё правильно сделали, это вопрос к ним. В самом SDK никаких таких проверок нет, соответственно ошибку эту исправить мы не можем.

Также очень рекомендую [спросить у нас на канале](https://t.me/phpcdeksdk). Может быть там есть кто-то, кто тоже сталкивался с такой же ошибкой.

**Comment by oleglap68** [comment]
Хорошо, спасибо. Канал ваш пока недоступен. Попробую зайти позже.

**Comment by sanmai** [comment]
Можем ли мы считать эту проблему исчерпавшей себя?
