### ISSUE TITLE
sendCalculationWithTariffListRequest возвращает ошибку 500

### ISSUE THREAD

**Issue by yurcha** [sanmai/cdek-sdk#56]
**Опишите проблему**
Сайт http://lk.shop-delivery.ru/admin
test@test.ru
123456
Калькулятор выдает ошибку 500.

Если нажать Расчитать (можно не заполнять города), то какое то время запрос висит, в конце выдает 500 ошибку.
![Безымянный](https://user-images.githubusercontent.com/31619105/61692775-eac30780-ad36-11e9-9d3e-4772ddc31a74.png)

Вот функция, которая выполняется:

```
public function getCalcPrice(\CdekSDK\CdekClient $client, Request $request) 
{
        $user_account = Auth::user()->account;
        $req = new Requests\CalculationWithTariffListAuthorizedRequest();
        $req->setSenderCityId($request->fromCode)
            ->setReceiverCityId($request->toCode)
            ->addTariffToList(1)
            ->addTariffToList(11)
            ->addTariffToList(12)
            ->addTariffToList(10)
            ->addPackage([
                "weight" => $request->WeightPackage,
                "length" => $request->SizeA,
                "width"  => $request->SizeB,
                "height" => $request->SizeC,
            ]);
        $response = $client->sendCalculationWithTariffListRequest($req);

        $arResult = array("error"=>"Повторите запрос позже");

        echo json_encode($arResult);
    }
```
Если удалить 
```
$response = $client->sendCalculationWithTariffListRequest($req);
```
то функция выполняется до конца.

**composer update** Сделано. Все пакеты актуальные.
Проект развернут на beget.
Локальный проект (на openserver) работает корректно.

**Comment by sanmai** [comment]
Пришлите лог запросов и ответов, пожалуйста. [Как получить логи.](https://cdek-sdk.readthedocs.io/#DebuggingLogger)

**Comment by sanmai** [comment]
То есть тот же самый код работает в локальном проекте, но при деплое - не работает? С теми же самыми ключами?

Так или иначе, нужны логи. С ними или мы найдём проблему, или вам будет прямая дорога в поддержку СДЭК. Они тоже попросят логи.

**Comment by yurcha** [comment]
Пытаюсь воспользоваться "Пример класса, реализующего минимальный интерфейс." Добавил этот класс к себе в проект. Как мне получить логи?

**Comment by sanmai** [comment]
Что непонятно [в этой инструкции](https://cdek-sdk.readthedocs.io/#DebuggingLogger)?

**Comment by yurcha** [comment]
Сделал я логирование, но при этой ошибке ничего в логи не пишется.

**Comment by sanmai** [comment]
Значит это не проблема SDK.

**Comment by yurcha** [comment]
Понимаю. Посоветовать что то можете? сервер проверить? на сервере php 7.1 стоит.

**Comment by iamwildtuna** [comment]
Посмотреть логи PHP и информацию о ошибке :)

**Comment by yurcha** [comment]
переделал с POST на GET
Ларавел вывел ошибку
GuzzleHttp\Exception\ConnectException thrown with message "cURL error 28: Connection timed out after 60001 milliseconds (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)"

**Comment by iamwildtuna** [comment]
Судя по всему СДЭК не ответил за 60 секунд

**Comment by sanmai** [comment]
Или не ответил вообще, потому что ваш IP забанен.

**Comment by iamwildtuna** [comment]
Но тогда в логах должен быть запрос, видимо, логгер не правильно подключили

**Comment by yurcha** [comment]
логер локально нормально отрабатывает. пишет, что города не указаны, например. На сервере пробовал просто текст в лог записать - работает. 
Ладно буду дальше со сдеком и сервером разбираться. Спасибо

**Comment by sanmai** [comment]
Ещё раз, `cdek-requests.log` у вас пустой?

**Comment by yurcha** [comment]
я через монолог сделал

**Comment by sanmai** [comment]
А уровень логгирования какой у вас настроен? `DEBUG`?

**Comment by yurcha** [comment]
да

**Comment by yurcha** [comment]
```
$logger = new Logger('my_logger');
        $logger->pushHandler(new StreamHandler(__DIR__.'/my_app.log', Logger::DEBUG));
       $logger->pushHandler(new FirePHPHandler());
        $client->setLogger($logger);
```

**Comment by sanmai** [comment]
Локально в лог идёт запись?

**Comment by yurcha** [comment]
да. только там не 500 ошибка, а не заполненные поля, например.

**Comment by sanmai** [comment]
А 500 ошибка в логах как выглядит?

**Comment by yurcha** [comment]
проблема в том, что он эту ошибку не пишет в логи((

**Comment by sanmai** [comment]
В других логах что-то да должно быть. Ошибка 500 без соответствующей записи в логе - очень редкое явление.

**Comment by yurcha** [comment]
[laravel.log](https://github.com/sanmai/cdek-sdk/files/3421204/laravel.log)
Вот лог от ларавел

**Comment by yurcha** [comment]
как оказалось, проблема не только в методе расчета стоимости. печать накладных туже ошибку выдает. значит у сервера и сдэка какие то терки. не хотя общаться друг с другом.
