### ISSUE TITLE
Не получается добавить тег из документации СДЭК

### ISSUE THREAD

**Issue by yurcha** [sanmai/cdek-sdk#57]
**Опишите проблему**
В документации сдека есть тег **1.7.26 | Comment | Комментарий особые отметки по заказу**
Он находится в блоке **1.7.25 | Seller | Реквизиты истинного продавца**
Но в классе **Seller** нет возможно добавить **$Comment**

http://joxi.ru/Q2Kyg8vhLaKg4r

[Ссылка на документацию](https://confluence.cdek.ru/pages/viewpage.action?pageId=15616129#id-%D0%9F%D1%80%D0%BE%D1%82%D0%BE%D0%BA%D0%BE%D0%BB%D0%BE%D0%B1%D0%BC%D0%B5%D0%BD%D0%B0%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D0%BC%D0%B8(v1.5)-4.2.1.%D0%9E%D0%BF%D0%B8%D1%81%D0%B0%D0%BD%D0%B8%D0%B5%D0%BF%D0%B5%D1%80%D0%B5%D0%B4%D0%B0%D0%B2%D0%B0%D0%B5%D0%BC%D1%8B%D1%85%D0%BF%D0%BE%D0%BB%D0%B5%D0%B9%D0%B7%D0%B0%D0%BF%D1%80%D0%BE%D1%81%D0%B0)

**Comment by sanmai** [comment]
Посмотрите на нумерацию. 1.7.25 - это продавец. 1.7.25.5 - это поле объекта продавца. 1.7.26 - это уже поле объекта уровнем выше (заказа), точно так же как и 1.7.27.
