### ISSUE TITLE
Поля SendCity и RecCity в объекте Order

### ISSUE THREAD

**Issue by sanmai** [sanmai/cdek-sdk#61]
> При вызове DeliveryRequest - в тэг Order добавляются вложенные тэги SendCity и RecCity, зачем они там? 

Следует рассмотреть возможность убрать эти поля из XML, или из объекта вообще. Ранее такие поля были в ответе на запрос информации о заказе. Возможно они там ещё есть.

**Comment by admmatrix** [comment]
У вас в запросе строчки лишние, т.к вы тоже самое указывали в order
<SendCity Code="44"/>
<RecCity Code="4961"/>
Строчки Sender Name="Тест" Company="ООО Акрист"> необходимо указывать в тэге order.

**Comment by sanmai** [comment]
Пример кода, который не должен приводить к появлению этих тегов в итоговом XML:
![photo_2019-08-28_12-23-58](https://user-images.githubusercontent.com/139488/63823416-c63df900-c98e-11e9-96ee-3474398d6266.jpg)

**Comment by sanmai** [comment]
Пример корректного запроса на доставку:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<DeliveryRequest OrderCount="1" Number="8495" ForeignDelivery="true" Currency="RUB" Date="2019-08-24" Account="1" Secure="1">
<Order SendCityCode="44" RecCityCode="4961" ClientSide="sender" Number="8495" RecipientCompany="еуые" RecipientName="еуые" Phone="89111113322" TariffTypeCode="11" Comment="Индекс получателя:">
<Sender Name="Тест" Company="ООО Ааааа">
<Phone>89111113322</Phone>
</Sender>
<Address Street="asfasfas" House="1" Flat="1"/>
<Package Number="1" BarCode="1" Weight="500" SizeA="1" SizeB="1" SizeC="1" Comment="1"/>
</Order>
</DeliveryRequest>
```

**Comment by sanmai** [comment]
@admmatrix спасибо за помощь!
