### ISSUE TITLE
Теряется ключ cashOnDelivery при расчете стоимости доставки

### ISSUE THREAD

**Issue by ykrasnoborodikova** [sanmai/cdek-sdk#63]
При расчете доставки, например в город: "Ковылкино, Мордовия респ., Россия" по тарифу id=1 наложенный платеж недоступен (на 23 августа 2019).
API сдэк возвращает ключ `cashOnDelivery = 0`
В своей программе я не могу получить доступ к этой информации через объект $response:
```
$request = new Requests\CalculationAuthorizedRequest;
$request->setSenderCityId(288)->setReceiverCityId(2766)->setTariffId(1)->addPackage(['weight' => 1,'length' => 4,'width' => 4,'height' => 4]);
$response = $client->sendCalculationRequest($request);
$response->getCashOnDelivery(); // Аттрибута не существует
```

https://confluence.cdek.ru/pages/viewpage.action?pageId=15616129

4.14.1.2. Формат ответа

cashOnDelivery | Ограничение оплаты наличными, появляется только если оно есть

Нужно добавить в файле `Responses/Types/Result.php` аттрибут `$cashOnDelivery`
И обновить документацию (добавить метод `getCashOnDelivery()`)

**Comment by sanmai** [comment]
Огромное спасибо за такой детальный отчёт о проблеме с примером запроса! Исправление будет в ближайшем релизе. Если ничего не помешает, через час или два.
