### ISSUE TITLE
Указание даты при создании заказа

### ISSUE THREAD

**Issue by ykrasnoborodikova** [sanmai/cdek-sdk#65]
https://confluence.cdek.ru/pages/viewpage.action?pageId=15616129
4.2.1. Описание передаваемых полей запроса
Как правильно передать параметр 1.2 | **Date**?

В редких случаях, если:
1. его не передавать и
2. часовой пояс установлен на +1-8 МСК и
3. время в москве, например 23:10, а на сервере 00:10,

То получается следующая ситуация: заказ создается, но в личном кабинете СДЭК его нет. Это происходит, поскольку заказ создается с отправкой "завтра" (относительно Москвы). Спустя 50 минут заказ появится в личном кабинете СДЭК (в Москве будет 00:00).

**Comment by sanmai** [comment]
В документации ничего такого не указано. Действительно есть такое поведение? Может быть это обычная задержка при обновлении БД? Как такое неожиданное поведение комментирует техническая поддержка СДЭК?

Дату запроса можно подать вторым аргументом к каждому методу отправки запроса, но не могу гарантировать что этот вариант сохранится в следующей мажорной версии, если, конечно, не появится упоминание этого интересного поведения в документации.

**Comment by ykrasnoborodikova** [comment]
Это нормальное поведение из-за разных часовых поясов. В личном кабинете СДЭК можно также наблюдать такую ситуацию, если создавать заказы через импорт (https://lk.cdek.ru/import-invoice/index) и дату заказа указать как в примере - 6 сентября по Владивостоку (+7 мск), в то время как в Москве все еще 5 сентября, то заказ в списке появится только когда в Москве наступит 6 сентября.
Не проверяла, но насколько понимаю, можно решить это, если часовой пояс установить МСК.
В идеале хотелось бы как-то дату передавать. А еще лучше, возможно автоматом при подстановке даты в запрос учитывать часовой пояс, чтобы не делать лишних правок в коде приложения

**Comment by sanmai** [comment]
Автоматом - то есть чтобы ставилась дата по какому часовому поясу?

**Comment by ykrasnoborodikova** [comment]
По часовому поясу Москвы, так как по нему работает СДЭК
Влияние на другие функции - не знаю. Пока в такой ситуации просто ждали до утра и продолжали работу в обычном режиме.

**Comment by greabock** [comment]
Тип поля указан как:
> Date Time – дата и время в формате ISO 8601:2004:YYYY-MM-DDThh:mm:ss+hh:mm

То есть, по логике, смещение по часовому поясу должно учитываться, СDEK'ом.

> А еще лучше, возможно автоматом при подстановке даты в запрос учитывать часовой пояс, чтобы не делать лишних правок в коде приложения.

Прежде чем вносить такие изменения, 
1. Нужно доподлинно убедится, что проблема возникает не от того что у вас неверно указан часовой пояс для объекта DateTime.
2. Уточнить у CDEK что это фича, а не баг, и что они не изменят это поведение, когда им вдруг вздумается.

В качестве временного (а возможно, и постоянного) решения:

Можно передавать дату с явно установленным с московским часовым поясом и поправкой на него. Тогда, не зависимо от исхода по данному вопросу (исправят это в CDEK ,  или в этом SDK, или же вообще всё останется как есть) ваш код в любом случае останется рабочим.

**Comment by sanmai** [comment]
#69 делает так чтобы дата всегда передавалась с часовым поясом, потому, если на сервере стоит правильный часовой пояс, в следующей версии ничего вообще не должно будет быть нужно делать чтобы всё работало правильно.

**Comment by ykrasnoborodikova** [comment]
Спасибо!

**Comment by sanmai** [comment]
@ykrasnoborodikova пожалуйста проверьте что проблема действительно ушла.
