### ISSUE TITLE
Выводит сообщение (ERR_AUTH) при вызове метода sendStatusReportRequest

### ISSUE THREAD

**Issue by pamparam83** [sanmai/cdek-sdk#70]
пытаюсь получить статусы заказов
пробовал под тестовыми данными СДЭК
<skip> - логин
<skip> - пароль
отрабатывает нормально 

но когда меняю на свои вылетает ошибка "Интернет-магазин не идентифицирован: "

пробовал все реализовать как в файле examples/150_StatusReportRequest.php
для своих учеток базовый урл менял на боевой и тестовый , результат одинаковый.
errorCode = ERR_AUTH
Хотелось бы понять почему так происходит ?
почему не происходит авторизация ?

**Comment by sanmai** [comment]
Если с тестовыми реквизитами авторизация проходит, то это проблема не в SDK, а в реквизитах. Рекомендую [обратиться в поддержку СДЭК напрямую](https://www.cdek.ru/clients/integrator.html).
