### ISSUE TITLE
Ошибка в доках или я тупой?

### ISSUE THREAD

**Issue by antonwantstosleep** [sanmai/cdek-sdk#74]
**Опишите проблему**
Делаю получение списка ПВЗ по https://cdek-sdk.readthedocs.io/#PvzListRequest.

На строчке:
`$request->setType(PvzListRequest::TYPE_ALL);`
получаю ошибку:
`PHP Uncaught Error: Class 'PvzListRequest' not found.`

Если заменить на `$request->setType(Requests\PvzListRequest::TYPE_ALL);` то всё работает.

Ошибка в примере или я что-то делаю не так?

**Comment by greabock** [comment]
Опечатка в примере, конечно же.
