### ISSUE TITLE
Можно ли получить список ПВЗ сразу с посчитанным сроком доставки?

### ISSUE THREAD

**Issue by KoIIIeY** [sanmai/cdek-sdk#76]
Можно ли получить список ПВЗ сразу с посчитанным сроком доставки? (соответсвенно, я не против в запрос со списком пвз добавить размеры и вес товара)

Найти в документации такое что-то не могу, но мне всегда казалось что для доставки это очевидное поведение.

**Comment by sanmai** [comment]
В официальном описании API есть такие данные?

**Comment by KoIIIeY** [comment]
Вот не нашел, надеялся что у вас есть решение )
А так получается, я должен на каждый пвз делать запрос на рассчет что ли?

**Comment by sanmai** [comment]
Если в официальном API нет другого способа, то и тут тоже нет. К сожалению.

Попробуйте написать в поддержку СДЭК. Может быть они пойдут вам на встречу.
