### ISSUE TITLE
Пара вопросов разом

### ISSUE THREAD

**Issue by KoIIIeY** [sanmai/cdek-sdk#77]
1) Как делать заказ на доставку в ПВЗ? Просто адрес указывать от ПВЗ?

2) Можно ли получить только те города и регионы, где есть ПВЗ?

**Comment by sanmai** [comment]
Здравствуйте. [Официальная документация](https://confluence.cdek.ru/x/gUju) отвечает на ваши вопросы?

**Comment by KoIIIeY** [comment]
Написано задать PvzCode в Address. Тобишь, в
$order->setAddress(Common\Address::create([
    'Street'  => 'Холодильная улица',
    'House'   => '16',
    'Flat'    => '22',
]));

добавить еще и PvzCode ? 

И в вашем примере дважды используется сетАддресс

$order->setSender(Common\Sender::create([
    'Company' => 'ЗАО «Рога и Копыта»',
    'Name'    => 'Петр Иванов',
    'Phone'   => '+7 (283) 101-11-20',
])->setAddress(Common\Address::create([
    'Street' => 'Морозильная улица',
    'House'  => '2',
    'Flat'   => '101',
])));

$order->setAddress(Common\Address::create([
    'Street'  => 'Холодильная улица',
    'House'   => '16',
    'Flat'    => '22',
]));

Морозильная улица - это адрес где забрать, а холодильная - куда доставить?

**Comment by sanmai** [comment]
Цитата из документации:

> Адрес доставки. В зависимости от режима доставки необходимо указывать либо атрибуты «Street», «House», «Flat» - доставка до адресата получателя, либо «PvzCode» - самозабор 

Пожалуйста, пользуйтесь документацией.
