### ISSUE TITLE
ПОД v2.0

### ISSUE THREAD

**Issue by greabock** [sanmai/cdek-sdk#78]
C 27 января 2020 будет открыта версия ПОД 2.0. По личному опыту поддержки API могу сказать, что поддержка старого API, если и не сломается, то будет стагнировать. Есть ли планы по открытию ветки 2.0?

**Comment by sanmai** [comment]
Если там будут какие-то фичи, которых нет в старой версии, то это стоит будет сделать. Скорее всего лучше будет не ветку, а отдельный проект - так как новое API существенно отличается и по набору ключей, и по формату подачи.

В целом я не вижу проблем в реализации нового API по тем же самым принципам что и это.

**Comment by greabock** [comment]
Предлагаю,сделать именно ветку, чтобы не терять пользовательскую базу.

API этого SDK в целом стабильно и можно синхронизировать версии веток с версиями ПОД, а исправления и обновления делать в рамках патч версии.

Мне кажется, что так пользователям будет понятнее.

**Comment by sanmai** [comment]
Делать всё в одном проекте имеет смысл если подразумевается что долгое время новое и старое API нужно будет использовать бок о бок. [Судя по описанию нового API](https://confluence.cdek.ru/pages/viewpage.action?pageId=29923741) можно предположить что новое будет полностью заменять новое. Таким образом, для новых пользователей будет проще если им не придется на каждом шагу натыкаться на фрагменты старого API. Например, не придется выбирать между старым и новым объектом для получателя или заказа. Не будет связанных с этим ошибок.

Разрабатывать и поддерживать два таких отдельных проекта тоже будет проще, хотя бы потому что релиз одного не будет приводить к релизу другого.

Поставить всюду гиперссылки туда и обратно не проблема вообще.

**Comment by sanmai** [comment]
Для нового API есть официальный SDK от самих СДЭК:
 - http://cdek-it-sdk20.rtfd.io/
 - https://github.com/cdek-it/sdk2.0

Несмотря на то, что новый SDK использует очень много идей из этого, нашего и вашего, проекта, не могу сказать что мне на 100% нравится так, как сделан этот новый SDK, но пока, я думаю, можно утверждать что вопрос создания ещё одного другого SDK можно считать закрытым.
