### ISSUE TITLE
Отвалился CitiesRequest

### ISSUE THREAD

**Issue by kosuha606** [sanmai/cdek-sdk#82]
Привет, столкнулся с проблемой что этот урл больше не работает как раньше.
http://integration.cdek.ru/v1/location/cities/xml

Может кто-то знает как вернуть этот функционал по поиску города?
Пока не нашел почему это перестало работать но ищу

У меня карта юзер вводит навзание города, выбирает из списка и получает cityId потом я получал от этой точки API lat lng для города чтобы переключить карту, но видимо придется lat lng получать от первого пункта ПВЗ чтоли

**Comment by TiGR** [comment]
Если вдруг заработает, пока что он отдаёт 500 статус и в теле:

    {"alerts":[{"type":"danger","errorCode":"internal_error"}]}

**Comment by sanmai** [comment]
Не работает и XML, и JSON варианты для этого запроса. Скорее всего стоит обратиться в поддержку: это проблема на стороне СДЭК. 

Также можно отметить что [в канале](https://t.me/phpcdeksdk) последние дни много жалоб на некорректную работу API.

**Comment by TiGR** [comment]
КМК, если это стандартный у них вариант поведения API в случае отказа, то стоит сделать чтобы библиотека корректно это обрабатывала и метод `getMessages` нормально возвращал `500` и `internal_error`, чтобы можно было это спокойно обрабатывать и не тратить кучу времени на то, чтобы разобраться с проблемой.

**Comment by sanmai** [comment]
Да, можно попробовать такую ошибку обрабатывать.
