### ISSUE TITLE
Проблема отображения адреса получателя в личном кабинете клиента CDEK

### ISSUE THREAD

**Issue by Alfabrega** [sanmai/cdek-sdk#84]
При регистрации заказа через api любой версии , тариф 137, указываем адрес получателя 
```php
$order->setAddress(Common\Address::create([
    'Street' => 'Холодильная улица',
    'House'  => '16',
    'Flat'   => '22',
])); 
```
При Редактирование заказа в личном кабинете CDEK, отображается неверная информация, в разделе "Получатель" отображается Улица *

   Холодильная улица
   Дом * / Квартира (офис) *
   16  /   16.

В данном примере вместо Квартиры подставляется Дом. Как правильно сформировать адрес доставки с учетом квартиры? в новом api v2.0 та же проблема.

С Уважением, Василий Недвигин.

**Comment by sanmai** [comment]
Здравствуйте. Если на квитанции адрес правильный, то это проблема отображения данных в ЛК. Такие проблемы были известны и раньше. К сожалению, помочь с ними могут только сами СДЭК.
