### ISSUE TITLE
Задание отправителя для интернет магазина

### ISSUE THREAD

**Issue by rassabin** [sanmai/cdek-sdk#86]
В процессе создания заказа с помощью тестового аккаунта интернет магазина  необходимо задать отправителя (адрес отправителя и интернет магазина может отличаться). При задании таким образом получаем ошибку "Client side is empty".
При задании ClientSide = sender (и любых других) , ошибка "Несоответствие выбранной услуги типу заказа" 
Хотя без доп графы $order->setSender таких ошибок не возникает, но задать адрес отправителя необходимо.
В документации указано
что можно указывать для интернет магазина отправителя (1.6.15 пункт).

**Comment by sanmai** [comment]
Что ответила вам поддержка СДЭК?

**Comment by rassabin** [comment]
СДЭК требуют XML запрос для проверки, но дело в том что когда я переписал запрос для стандартного API через XML, то проблем нет.

> Что ответила вам поддержка СДЭК?

**Comment by sanmai** [comment]
Всё правильно требуют. [Как получить XML запроса.](https://cdek-sdk.readthedocs.io/#DebuggingLogger)

Если есть XML корректного и некорректного запросов, я вам подскажу что нужно у вас в коде поменять чтобы получить корректный запрос. Если же XML нет, то помочь не получится.
