### ISSUE TITLE
Получение накладной на доставку.

### ISSUE THREAD

**Issue by ArtiomKolesnikov** [sanmai/cdek-sdk#87]
Здравствуйте. Пользуюсь Вашей библиотекой уже давно, но только для калькуляции стоимости доставки и получения списка ПВЗ. Третьего дня, решили мы воспользоваться апи для формирования накладной на доставку, нас интересуют исключительно тарифы для ИМ 136/137 и 233/234. 

Если пользуюсь "[Регистрация заказа от интернет-магазина](https://cdek-sdk.readthedocs.io/#DeliveryRequest)", то "[Печать квитанции к заказу](https://cdek-sdk.readthedocs.io/#PrintReceiptsRequest)" выдаёт накладную без стоимости доставки. Если использую "[Регистрация заказа на доставку](https://cdek-sdk.readthedocs.io/#AddDeliveryRequest)", то в ответ получаю "Несоответствие выбранной услуги типу заказа". 

Отправка из Краснодара в Новосибирск считается через калькуляцию, есть тарифы 233/234, а хочу получить накладную, говорит о несоответствии услуги. Помогите нам!

**Comment by sanmai** [comment]
Не похоже, чтобы это был дефект SDK. Поддержка СДЭК что-то вам отвечает?

**Comment by ArtiomKolesnikov** [comment]
Просят предоставить xml запрос к их апи, говорю им что работаю с sdk
которая заявлена на их же сайте, но они как буд-то не читают текст моих
сообщений. Если честно, то задолбался уже ковыряться в их документации,
авторизоваться даже не получается ни по апи V1.5 ни по V2.0

вт, 26 мая 2020 г. в 12:47, Alexey Kopytko <notifications@github.com>:

**Comment by sanmai** [comment]
Это корректная просьба. [Как получить XML запроса.](https://cdek-sdk.readthedocs.io/#DebuggingLogger)

**Comment by ArtiomKolesnikov** [comment]
Спасибо! Да, я знаю об этом, в документации читал, у меня проект на Laravel
5.8, но логи не пишутся, и ошибок никаких не показывает. Я просто разобрал
сам php-sdk и там при помощи dd() увидел что он отправляет. Только
поддержка молчит.

вт, 26 мая 2020 г. в 12:57, Alexey Kopytko <notifications@github.com>:

**Comment by sanmai** [comment]
Какой уровень отладки у вас в логах? Должен быть debug как минимум.

**Comment by ArtiomKolesnikov** [comment]
Был exception поставил debug, но всё равно не пишет, права выставил если что. Та ладно, я уже  своё простое логирование сделал. Волнует то что сдэк не отвечает уже больше суток, отправил им xml запроса и ответа, написал свою обёртку на их голый апи, получаю тот же ответ что и через ваше sdk " Несоответствие выбранной услуги типу заказа ". Как то вот так...

**Comment by ArtiomKolesnikov** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<DeliveryRequest OrderCount="1" Number="212297" ForeignDelivery="" Currency="RUB" Date="2020-05-26 14:13:34"
                 Account="786623f04fxxxxxxxxxxxxx" Secure="a8bxxxxxxxxxxxxxxxxxxxxxxxxxxx">
    <Order SendCityCode="435" RecCityPostCode="630001" Number="212297" ClientSide="sender"
           RecipientCompany="Петров и партнёры, ООО" RecipientName="Иван Петров" RecipientEmail="petrov@test.ru"
           Phone="+7 (383) 202-22-50" TariffTypeCode="233" Comment="Это тестовый заказ">
        <Address Street="Холодильная улица" House="18" Flat="22"/>
        <Package Number="212297" BarCode="212297" Weight="500" SizeA="10" SizeB="10" SizeC="10"
                 Comment="Обязательное описание вложения">
            <Item WareKey="NN0001" Cost="500" Payment="500" Weight="250" Amount="2" Comment="Test item"/>
        </Package>
        <Sender Name="Петр Иванов" Company="ЗАО «Рога и Копыта">
            <Address Street="Морозильная улица" House="2" Flat="101"/>
            <Phone><![CDATA[+7 (283) 101-11-20]]></Phone>
        </Sender>
    </Order>
</DeliveryRequest>

**Comment by ArtiomKolesnikov** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<DeliveryRequest OrderCount="1" Number="212297" ForeignDelivery="" Currency="RUB" Date="2020-05-26 14:13:34"
                 Account="786623f04fxxxxxxxxxxxxx" Secure="a8bxxxxxxxxxxxxxxxxxxxxxxxxxxx">
    <Order SendCityCode="435" RecCityPostCode="630001" Number="212297" ClientSide="sender"
           RecipientCompany="Петров и партнёры, ООО" RecipientName="Иван Петров" RecipientEmail="petrov@test.ru"
           Phone="+7 (383) 202-22-50" TariffTypeCode="233" Comment="Это тестовый заказ">
        <Address Street="Холодильная улица" House="18" Flat="22"/>
        <Package Number="212297" BarCode="212297" Weight="500" SizeA="10" SizeB="10" SizeC="10"
                 Comment="Обязательное описание вложения">
            <Item WareKey="NN0001" Cost="500" Payment="500" Weight="250" Amount="2" Comment="Test item"/>
        </Package>
        <Sender Name="Петр Иванов" Company="ЗАО «Рога и Копыта">
            <Address Street="Морозильная улица" House="2" Flat="101"/>
            <Phone><![CDATA[+7 (283) 101-11-20]]></Phone>
        </Sender>
    </Order>
</DeliveryRequest>

**Comment by ArtiomKolesnikov** [comment]
`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><response><Order ErrorCode="ERR_INVALID_TARIFF_WITH_ORDERTYPE" Msg="Несоответствие выбранной услуги типу заказа"/><Order Msg="Добавлено заказов 0"/><TraceId>9c6aa27720bd0398</TraceId></response>`

**Comment by ArtiomKolesnikov** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<DeliveryRequest OrderCount="1" Number="212297" ForeignDelivery="" Currency="RUB" Date="2020-05-26 14:13:34"
                 Account="786623f04fxxxxxxxxxxxxx" Secure="a8bxxxxxxxxxxxxxxxxxxxxxxxxxxx">
    <Order SendCityCode="435" RecCityPostCode="630001" Number="212297" ClientSide="sender"
           RecipientCompany="Петров и партнёры, ООО" RecipientName="Иван Петров" RecipientEmail="petrov@test.ru"
           Phone="+7 (383) 202-22-50" TariffTypeCode="233" Comment="Это тестовый заказ">
        <Address Street="Холодильная улица" House="18" Flat="22"/>
        <Package Number="212297" BarCode="212297" Weight="500" SizeA="10" SizeB="10" SizeC="10"
                 Comment="Обязательное описание вложения">
            <Item WareKey="NN0001" Cost="500" Payment="500" Weight="250" Amount="2" Comment="Test item"/>
        </Package>
        <Sender Name="Петр Иванов" Company="ЗАО «Рога и Копыта">
            <Address Street="Морозильная улица" House="2" Flat="101"/>
            <Phone><![CDATA[+7 (283) 101-11-20]]></Phone>
        </Sender>
    </Order>
</DeliveryRequest>`

**Comment by ArtiomKolesnikov** [comment]
Ответ и запрос

**Comment by sanmai** [comment]
Эти исходники вам надо дать поддержке, и они уже скажут где и что вы делаете не так.
