### ISSUE TITLE
Количество ПВЗ

### ISSUE THREAD

**Issue by alexshimkin** [sanmai/cdek-sdk#88]
Заметил, что SDK выдает меньше пунктов выдачи, чем по прямому запросу на api.

Для Люберец:
CdekSDK\Requests\PvzListRequest Object ( [type:protected] => ALL [cityId:protected] => 57 [regionId:protected] => [countryId:protected] => [countryIso:protected] => [cityPostCode:protected] => [haveCashless:protected] => [isDressingRoom:protected] => [allowedCod:protected] => [weightMax:protected] => [lang:protected] => [takeOnly:protected] => ) 
выдает 2 ПВЗ

Аналогичный (?) запрос http://integration.cdek.ru/pvzlist/v1/xml?cityid=57 выдает 3 ПВЗ. В Троицке и Москве тоже выводятся не все пункты, дальше не тестировал.

Что может быть причиной и как это исправить?

**Comment by sanmai** [comment]
Покажите как выглядит ваш запрос в коде.

**Comment by sanmai** [comment]
С таким примером, как ниже, у меня выдает ровно три. Это точно ошибка где-то у вас.

```php
<?php
require "vendor/autoload.php";

use CdekSDK\Requests;

$client = new \CdekSDK\CdekClient();

$request = new Requests\PvzListRequest();
$request->setCityId(57);

$response = $client->sendPvzListRequest($request);

if ($response->hasErrors()) {
    // обработка ошибок
}

foreach ($response as $item) {
    /** @var \CdekSDK\Common\Pvz $item */

    // всевозможные параметры соответствуют полям из API СДЭК
    $item->Code;
    $item->Name;
    $item->Address;

    foreach ($item->OfficeImages as $image) {
        $image->getUrl();
    }
}
```

**Comment by alexshimkin** [comment]
Согласен, воспроизводится. Буду искать косяки...

**Comment by sanmai** [comment]
Попробуйте [подключить отладку](https://cdek-sdk.readthedocs.io/#DebuggingLogger) и посмотреть, что за запрос вы делаете на самом деле.

**Comment by alexshimkin** [comment]
Все оказалось до ужаса просто :)

У меня был включен тестовый доступ
$client = new \CdekSDK\CdekClient($this->auth_login, $this->auth_password, new \GuzzleHttp\Client(['base_uri' => 'https://integration.edu.cdek.ru',]));

При переходе на боевой все наладилось. Хотя выглядит это все равно странно. Мне казалось, отличие тестового доступа от боевого только в записи изменений. При чем здесь количество пунктов выдачи? Но если в вашем коде включить тестовый доступ, тоже находится только 2 ПВЗ...
