### ISSUE TITLE
ошибка в автозагрузчик классов

### ISSUE THREAD

**Issue by Shaykhnazar** [sanmai/cdek-sdk#93]
**Есть ошибка в автозагрузчик классов**
когда  использую обычные команды ларавел артисан тогда появляестся таких ошибок.
![image](https://user-images.githubusercontent.com/49790448/91036630-1fcc1880-e621-11ea-9f76-09d58ed82602.png)

**Comment by sanmai** [comment]
Такая проблема была в одной из прошлых версий. Сделайте `composer update` и проверьте ещё раз, пожалуйста.

**Comment by Shaykhnazar** [comment]
все работает! после компосер упдате
